
#if !defined _CONFIG_H
#define _CONFIG_H

#define CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
#define CPACK_PACKAGE_VERSION_MAJOR 1
#define CPACK_PACKAGE_VERSION_MINOR 0
#define CPACK_PACKAGE_VERSION_PATCH 0

#endif
