name: Unit tests

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo rm -rf /home/linuxbrew
        sudo apt-get update -y
        sudo apt-get install libasound2-dev libsoundio-dev libsndfile1-dev fftw3-dev -y
        sudo apt-get install python3 python3-setuptools python3-pip 
        # Requires setuptools >= 62.1 for `python setup.py test`, as earlier versions
        # used a different build path to the .so file as located in tests/__init__.py
        # 2024-07-29: Require importlib_metadata for now due to this:
        #             https://github.com/pypa/setuptools/issues/4478
        sudo pip3 install -U pytest numpy scipy setuptools>=62.1.0 importlib_metadata
    - name: Configure
      run: mkdir build && cd build && cmake ..
    - name: Make
      run: cd build && make -j8
    - name: Python build
      run: python3 setup.py build
    - name: Install test dependencies
      run: pip3 install -e ".[test]"
    - name: Python test
      run: pytest
